name: CI pipeline

on:
  push:
    branches-ignore:
      - main

jobs:
  create-file:
    name: Create VARIABLES.md file on change within Branch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.0

    - name: Install rdflib
      run: pip install rdflib

    - name: Run Python script
      run: python3 src/readme_generator.py
      working-directory: ${{ github.workspace }}

    - name: Check for changes
      id: check_changes
      run: |
        if git status --porcelain | grep "VARIABLES.md"; then
          echo "CHANGES_FOUND=true" >> $GITHUB_OUTPUT
        else
          echo "CHANGES_FOUND=false" >> $GITHUB_OUTPUT
        fi
      continue-on-error: true
      working-directory: ${{ github.workspace }}

    - name: Commit and push changes
      if: steps.check_changes.outputs.CHANGES_FOUND == 'true'
      run: |
        git config --local user.email "justin.dex@msg-david.de"
        git config --local user.name "GitHub Action"
        git add */VARIABLES.md
        git commit -s -m "Add VARIABLES.md files"
        git push
      working-directory: ${{ github.workspace }}

  parse-turtle:
    name: Check syntax of all changed Turtle files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes in .ttl files
        id: check_ttl
        run: |
          git fetch origin main
          CHANGED_TTL=$(git diff --name-only origin/main -- '*.ttl')
          if [[ -n "$CHANGED_TTL" ]]; then
            echo "TTL_HAS_CHANGED=true" >> $GITHUB_ENV
            echo "CHANGED_TTL=$CHANGED_TTL" >> $GITHUB_ENV
          else
            echo "TTL_HAS_CHANGED=false" >> $GITHUB_ENV
            echo "Subsequent steps will be skipped as no .ttl files have changed."
          fi

      - name: Set up Python
        if: env.TTL_HAS_CHANGED == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.0

      - name: Install rdflib
        if: env.TTL_HAS_CHANGED == 'true'
        run: pip install rdflib

      - name: Run Python script for each changed .ttl file
        if: env.TTL_HAS_CHANGED == 'true'
        run: |
          for FILE in ${CHANGED_TTL}; do
            echo "Processing changed file: ${FILE}"
            python3 src/check_ttl_syntax.py "${FILE}"