name: Create VARIABLES.md file on change within Branch

on:
  push:
    branches-ignore:
      - main

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.0

    - name: Install rdflib
      run: pip install rdflib

    - name: Run Python script
      id: run_python_script
      run: |
        python_output=$(python3 src/readme_generator.py)
        echo "::set-output name=PYTHON_OUTPUT::$python_output"
      working-directory: ${{ github.workspace }}

    - name: Commit and push changes
      if: contains(steps.run_python_script.outputs.PYTHON_OUTPUT, 'Appended to VARIABLES.md')
      run: |
        git config --local user.email "justin.dex@msg-david.de"
        git config --local user.name "GitHub Action"
        git add */VARIABLES.md
        git commit -s -m "Add VARIABLES.md files"
        git push
      working-directory: ${{ github.workspace }}