name: Create Version Folder

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  create-version-folder:
    if: contains(github.event.pull_request.labels.*.name, 'create-version-folder')
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Get the base and head commit SHAs
      - name: Get the base and head commit SHAs
        id: commits
        run: |
          BASE_SHA=$(jq -r .pull_request.base.sha < $GITHUB_EVENT_PATH)
          HEAD_SHA=$(jq -r .pull_request.head.sha < $GITHUB_EVENT_PATH)
          echo "BASE_SHA=$BASE_SHA" >> $GITHUB_ENV
          echo "HEAD_SHA=$HEAD_SHA" >> $GITHUB_ENV

      # Get the list of changed files between the base and head commits
      - name: Get list of changed files
        id: changes
        run: |
          git fetch origin main
          git diff --name-only $BASE_SHA $HEAD_SHA > changed_files.txt
          echo "files=$(cat changed_files.txt | tr '\n' ' ')" >> $GITHUB_ENV
          echo "Changed files: $(cat changed_files.txt)"

      # Get the list of subfolders in the repository
      - name: Get list of subfolders
        id: subfolders
        run: |
          ls -d */ > subfolders.txt
          subfolders=$(cat subfolders.txt | tr '\n' ' ' | sed 's|/||g')
          if [ -z "$subfolders" ]; then
            echo "No subfolders found"
            exit 1
          fi
          echo "subfolders=$subfolders" >> $GITHUB_ENV
          echo "Subfolders: $subfolders"

      # Configure Git with user details
      - name: Configure Git
        run: |
          git config --global user.email "create-version-folder@gaia-x4plcaad.info"
          git config --global user.name "GitHub-Action"

      # Determine the version bump based on labels
      - name: Determine version bump
        id: version
        run: |
          LABELS=$(jq -r '.pull_request.labels[].name' < $GITHUB_EVENT_PATH)
          if echo "$LABELS" | grep -q "major"; then
            echo "bump=major" >> $GITHUB_ENV
          elif echo "$LABELS" | grep -q "minor"; then
            echo "bump=minor" >> $GITHUB_ENV
          elif echo "$LABELS" | grep -q "patch"; then
            echo "bump=patch" >> $GITHUB_ENV
          else
            echo "Error: No valid label found. Please add a 'major', 'minor', or 'patch' label to the pull request."
            exit 1
          fi
          echo "Version bump: ${{ env.bump }}"

      # Create version subfolders and update prefixes
      - name: Create version subfolders and update prefixes
        env:
          BUMP_TYPE: ${{ env.bump }}
        run: |
          python3 src/create_subfolder.py

      # Commit the changes and push to the current branch
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.head_ref }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit --signoff -m "Move files to version subfolders and update @prefix lines and @context entries"
            git pull --rebase origin ${{ env.BRANCH_NAME }}
            git push origin HEAD:${{ env.BRANCH_NAME }}
          else
            echo "No changes to commit"
          fi
