name: Create Releases

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-releases:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'create-releases')
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Get the base and head commit SHAs
      - name: Get the base and head commit SHAs
        id: commits
        run: |
          BASE_SHA=$(jq -r .pull_request.base.sha < $GITHUB_EVENT_PATH)
          HEAD_SHA=$(jq -r .pull_request.head.sha < $GITHUB_EVENT_PATH)
          echo "BASE_SHA=$BASE_SHA" >> $GITHUB_ENV
          echo "HEAD_SHA=$HEAD_SHA" >> $GITHUB_ENV

      # Get the list of changed files
      - name: Get list of changed files
        id: changes
        run: |
          git fetch origin main
          git diff --name-only $BASE_SHA $HEAD_SHA > changed_files.txt
          echo "files=$(cat changed_files.txt | tr '\n' ' ')" >> $GITHUB_ENV
          echo "Changed files: $(cat changed_files.txt)"

      # Get the list of subfolders
      - name: Get list of subfolders
        id: subfolders
        run: |
          ls -d */ > subfolders.txt
          subfolders=$(cat subfolders.txt | tr '\n' ' ' | sed 's|/||g')
          if [ -z "$subfolders" ]; then
            echo "No subfolders found"
            exit 1
          fi
          echo "subfolders=$subfolders" >> $GITHUB_ENV
          echo "Subfolders: $subfolders"

      # Configure Git
      - name: Configure Git
        run: |
          git config --global user.email "create-release-job@gaia-x4plcaad.info"
          git config --global user.name "GitHub-Action"

      # Determine version bump
      - name: Determine version bump
        id: version
        run: |
          LABELS=$(jq -r '.pull_request.labels[].name' < $GITHUB_EVENT_PATH)
          if echo "$LABELS" | grep -q "major"; then
            echo "bump=major" >> $GITHUB_ENV
          elif echo "$LABELS" | grep -q "minor"; then
            echo "bump=minor" >> $GITHUB_ENV
          elif echo "$LABELS" | grep -q "patch"; then
            echo "bump=patch" >> $GITHUB_ENV
          else
            echo "Error: No valid label found. Please add a 'major', 'minor', or 'patch' label to the pull request."
            exit 1
          fi
          echo "Version bump: ${{ env.bump }}"

      # Create version subfolders and update prefixes
      - name: Create version subfolders and update prefixes
        env:
          BUMP_TYPE: ${{ env.bump }}
        run: |
          python3 src/create_subfolder.py

      # Release Subfolders
      - name: Release Subfolders
        env:
          BUMP_TYPE: ${{ env.bump }}
        run: |
          python3 src/release_folder.py

      # Clean up temporary files
      - name: Clean up temporary files
        run: |
          rm -f versions.txt subfolders.txt changed_files.txt
