name: CI pipeline

on:
  push:
    branches-ignore:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install linter and formatter dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pre-commit install

      - name: Run pre-commit checks
        run: pre-commit run --all-files
