name: Upload files into FC on manual trigger (supports both create and update)

on:
  workflow_dispatch:
    inputs:
      folder_to_upload:
        description: "Folder to upload .ttl files from"
        required: true
      dry_run:
        description: "Indicates if the upload is a dry run (no changes will be made to FC)"
        default: true
        required: true

env:
  FOLDER_TO_UPLOAD: ${{ github.event.inputs.folder_to_upload }} # Folder to upload, this variable is specified by the user
  DRY_RUN: ${{ github.event.inputs.dry_run }} # dry run or not, this variable is specified by the user
  KEYCLOAK_USER: ${{ secrets.KEYCLOAK_USER }} # Keycloak Username, this is defined in a secret within github
  KEYCLOAK_PASSWORD: ${{ secrets.KEYCLOAK_PASSWORD }} # Keycloak Password, this is defined in a secret within github
  KEYCLOAK_CLIENT_SECRET_KEY: ${{ secrets.KEYCLOAK_CLIENT_SECRET_KEY }} # Keycloak Client Secret Key, this is defined in a secret within github

jobs:
  upload-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.0

      - name: Install required python libraries
        run: pip install -r requirements.txt

      - name: Run Python upload into FC
        run: python3 src/fc_upload_with_update.py
        working-directory: ${{ github.workspace }}
